working_dir: &working_dir ~/app 
.build_template: &script
  steps:
    - checkout
    - setup_remote_docker
    - run:    sleep 3m && docker pull
    
version: 2.0 
jobs: 
  build: 
    <<: *script
    parallelism: 15
    docker:
      - image: circleci/python:3.5
    
    
  build2: 
    <<: *script
    docker:
      - image: circleci/python:3.5
  
  
workflows: 
  version: 2 
  commit: 
    jobs: 
      - build
      - build2
     
    
